// Mock data for the PyroLedger prototype.
// All values are FICTIONAL sample data for UI demonstration only.
// No real explosive inventory, magazine coordinates, licenses, customers,
// or regulatory records are represented here.

import type {
  Product,
  InventoryLot,
  InventorySummaryRow,
  Magazine,
  LedgerEntry,
  CountSession,
  CountLine,
  VarianceCase,
  InspectionChecklistItem,
  MagazineInspection,
  DailyCloseRecord,
  Show,
  ShowPackageLine,
  LoadoutLine,
  ReturnLine,
  Shipment,
  ComplianceItem,
  DocumentRecord,
  AuditEvent,
  UserAccount,
  ReportDefinition,
} from './types'

// ---------------------------------------------------------------------------
// Products
// ---------------------------------------------------------------------------

export const products: Product[] = [
  {
    id: 'p-001',
    sku: 'DS-6IN-RED',
    name: '6" Chrysanthemum Display Shell — Red',
    manufacturer: 'Northwind Pyrotechnics (fictional)',
    category: 'display-shell',
    hazardDivision: '1.1G',
    unHazardId: 'UN0335',
    netExplosiveWeightG: 210,
    unitOfMeasure: 'each',
    storageGroup: 'A',
    active: true,
    notes: 'Standard aerial display shell. Sample record.',
  },
  {
    id: 'p-002',
    sku: 'DS-4IN-BLU',
    name: '4" Peony Display Shell — Blue',
    manufacturer: 'Northwind Pyrotechnics (fictional)',
    category: 'display-shell',
    hazardDivision: '1.3G',
    unHazardId: 'UN0335',
    netExplosiveWeightG: 95,
    unitOfMeasure: 'each',
    storageGroup: 'A',
    active: true,
  },
  {
    id: 'p-003',
    sku: 'CAKE-500-AST',
    name: '500-Shot Assorted Cake',
    manufacturer: 'Summit Effects Co. (fictional)',
    category: 'cake',
    hazardDivision: '1.4G',
    unHazardId: 'UN0336',
    netExplosiveWeightG: 3800,
    unitOfMeasure: 'each',
    storageGroup: 'B',
    active: true,
  },
  {
    id: 'p-004',
    sku: 'LIFT-3F-BP',
    name: 'Lift Charge — 3Fg Black Powder',
    manufacturer: 'Ridgeline Powder (fictional)',
    category: 'lift-charge',
    hazardDivision: '1.1D',
    unHazardId: 'UN0027',
    netExplosiveWeightG: 454,
    unitOfMeasure: 'lb',
    storageGroup: 'C',
    active: true,
    notes: 'Bulk propellant. Sample record.',
  },
  {
    id: 'p-005',
    sku: 'IGN-EM-01',
    name: 'Electric Match Igniter',
    manufacturer: 'Arc Ignition Systems (fictional)',
    category: 'igniter',
    hazardDivision: '1.4S',
    unHazardId: 'UN0454',
    netExplosiveWeightG: 2,
    unitOfMeasure: 'each',
    storageGroup: 'D',
    active: true,
  },
  {
    id: 'p-006',
    sku: 'DS-8IN-GLD',
    name: '8" Willow Display Shell — Gold',
    manufacturer: 'Northwind Pyrotechnics (fictional)',
    category: 'display-shell',
    hazardDivision: '1.1G',
    unHazardId: 'UN0335',
    netExplosiveWeightG: 480,
    unitOfMeasure: 'each',
    storageGroup: 'A',
    active: true,
  },
  {
    id: 'p-007',
    sku: 'ACC-QM-24',
    name: 'Quick Match — 24" Length',
    manufacturer: 'Arc Ignition Systems (fictional)',
    category: 'accessory',
    hazardDivision: '1.4G',
    unHazardId: 'UN0103',
    netExplosiveWeightG: 6,
    unitOfMeasure: 'each',
    storageGroup: 'D',
    active: false,
    notes: 'Deactivated SKU — retained for history.',
  },
]

// ---------------------------------------------------------------------------
// Magazines
// ---------------------------------------------------------------------------

export const magazines: Magazine[] = [
  {
    id: 'm-01',
    name: 'Magazine M-01',
    code: 'M-01',
    type: 'type-1',
    status: 'operational',
    location: 'West Yard — Bay 1 (sample)',
    capacityNewG: 2_000_000,
    currentNewG: 1_340_500,
    lotCount: 14,
    lastInspection: '2026-02-09T08:15:00Z',
    nextInspectionDue: '2026-02-16T08:00:00Z',
    lastDailyClose: '2026-02-11T18:30:00Z',
    flags: [],
  },
  {
    id: 'm-02',
    name: 'Magazine M-02',
    code: 'M-02',
    type: 'type-2',
    status: 'inspection-due',
    location: 'West Yard — Bay 3 (sample)',
    capacityNewG: 1_200_000,
    currentNewG: 980_200,
    lotCount: 9,
    lastInspection: '2026-02-03T08:00:00Z',
    nextInspectionDue: '2026-02-12T08:00:00Z',
    lastDailyClose: '2026-02-11T18:45:00Z',
    flags: ['review-required'],
  },
  {
    id: 'm-03',
    name: 'Magazine M-03',
    code: 'M-03',
    type: 'type-2',
    status: 'operational',
    location: 'East Yard — Bay 2 (sample)',
    capacityNewG: 1_200_000,
    currentNewG: 410_000,
    lotCount: 6,
    lastInspection: '2026-02-10T09:00:00Z',
    nextInspectionDue: '2026-02-17T09:00:00Z',
    lastDailyClose: '2026-02-11T19:00:00Z',
    flags: ['variance-detected'],
  },
  {
    id: 'm-04',
    name: 'Magazine M-04',
    code: 'M-04',
    type: 'type-3',
    status: 'maintenance',
    location: 'North Pad — Unit 1 (sample)',
    capacityNewG: 600_000,
    currentNewG: 0,
    lotCount: 0,
    lastInspection: '2026-01-28T10:00:00Z',
    nextInspectionDue: '2026-02-25T10:00:00Z',
    lastDailyClose: '2026-02-05T17:00:00Z',
    flags: ['missing-documentation'],
  },
]

// ---------------------------------------------------------------------------
// Inventory lots + summary
// ---------------------------------------------------------------------------

export const inventoryLots: InventoryLot[] = [
  {
    id: 'lot-1001',
    lotNumber: 'LOT-2026-0142',
    productId: 'p-001',
    productName: products[0].name,
    sku: 'DS-6IN-RED',
    quantity: 480,
    unitOfMeasure: 'each',
    magazineId: 'm-01',
    magazineName: 'Magazine M-01',
    receivedDate: '2026-01-18T10:20:00Z',
    manufactureDate: '2025-11-02T00:00:00Z',
    supplierLotRef: 'NW-5521-A',
    netExplosiveWeightG: 100_800,
    flags: [],
    sync: 'synced',
  },
  {
    id: 'lot-1002',
    lotNumber: 'LOT-2026-0143',
    productId: 'p-003',
    productName: products[2].name,
    sku: 'CAKE-500-AST',
    quantity: 60,
    unitOfMeasure: 'each',
    magazineId: 'm-01',
    magazineName: 'Magazine M-01',
    receivedDate: '2026-01-22T14:00:00Z',
    supplierLotRef: 'SE-8890',
    netExplosiveWeightG: 228_000,
    flags: [],
    sync: 'synced',
  },
  {
    id: 'lot-1003',
    lotNumber: 'LOT-2026-0151',
    productId: 'p-004',
    productName: products[3].name,
    sku: 'LIFT-3F-BP',
    quantity: 220,
    unitOfMeasure: 'lb',
    magazineId: 'm-02',
    magazineName: 'Magazine M-02',
    receivedDate: '2026-02-01T09:10:00Z',
    supplierLotRef: 'RL-3021',
    netExplosiveWeightG: 99_880,
    flags: ['review-required'],
    sync: 'pending',
  },
  {
    id: 'lot-1004',
    lotNumber: 'LOT-2026-0155',
    productId: 'p-006',
    productName: products[5].name,
    sku: 'DS-8IN-GLD',
    quantity: 120,
    unitOfMeasure: 'each',
    magazineId: 'm-03',
    magazineName: 'Magazine M-03',
    receivedDate: '2026-02-04T11:30:00Z',
    supplierLotRef: 'NW-5540-C',
    netExplosiveWeightG: 57_600,
    flags: ['variance-detected'],
    sync: 'error',
  },
  {
    id: 'lot-1005',
    lotNumber: 'LOT-2026-0160',
    productId: 'p-002',
    productName: products[1].name,
    sku: 'DS-4IN-BLU',
    quantity: 900,
    unitOfMeasure: 'each',
    magazineId: 'm-01',
    magazineName: 'Magazine M-01',
    receivedDate: '2026-02-06T08:45:00Z',
    supplierLotRef: 'NW-5602',
    netExplosiveWeightG: 85_500,
    flags: [],
    sync: 'synced',
  },
  {
    id: 'lot-1006',
    lotNumber: 'LOT-2026-0161',
    productId: 'p-005',
    productName: products[4].name,
    sku: 'IGN-EM-01',
    quantity: 5000,
    unitOfMeasure: 'each',
    magazineId: 'm-03',
    magazineName: 'Magazine M-03',
    receivedDate: '2026-02-07T13:15:00Z',
    supplierLotRef: 'ARC-1180',
    netExplosiveWeightG: 10_000,
    flags: [],
    sync: 'pending',
  },
]

export const inventorySummary: InventorySummaryRow[] = [
  {
    productId: 'p-001',
    sku: 'DS-6IN-RED',
    productName: products[0].name,
    category: 'display-shell',
    hazardDivision: '1.1G',
    totalQuantity: 480,
    unitOfMeasure: 'each',
    lotCount: 1,
    magazineCount: 1,
    totalNewG: 100_800,
    flags: [],
  },
  {
    productId: 'p-002',
    sku: 'DS-4IN-BLU',
    productName: products[1].name,
    category: 'display-shell',
    hazardDivision: '1.3G',
    totalQuantity: 900,
    unitOfMeasure: 'each',
    lotCount: 1,
    magazineCount: 1,
    totalNewG: 85_500,
    flags: [],
  },
  {
    productId: 'p-003',
    sku: 'CAKE-500-AST',
    productName: products[2].name,
    category: 'cake',
    hazardDivision: '1.4G',
    totalQuantity: 60,
    unitOfMeasure: 'each',
    lotCount: 1,
    magazineCount: 1,
    totalNewG: 228_000,
    flags: [],
  },
  {
    productId: 'p-004',
    sku: 'LIFT-3F-BP',
    productName: products[3].name,
    category: 'lift-charge',
    hazardDivision: '1.1D',
    totalQuantity: 220,
    unitOfMeasure: 'lb',
    lotCount: 1,
    magazineCount: 1,
    totalNewG: 99_880,
    flags: ['review-required'],
  },
  {
    productId: 'p-005',
    sku: 'IGN-EM-01',
    productName: products[4].name,
    category: 'igniter',
    hazardDivision: '1.4S',
    totalQuantity: 5000,
    unitOfMeasure: 'each',
    lotCount: 1,
    magazineCount: 1,
    totalNewG: 10_000,
    flags: [],
  },
  {
    productId: 'p-006',
    sku: 'DS-8IN-GLD',
    productName: products[5].name,
    category: 'display-shell',
    hazardDivision: '1.1G',
    totalQuantity: 120,
    unitOfMeasure: 'each',
    lotCount: 1,
    magazineCount: 1,
    totalNewG: 57_600,
    flags: ['variance-detected'],
  },
]

// ---------------------------------------------------------------------------
// Ledger
// ---------------------------------------------------------------------------

export const ledgerEntries: LedgerEntry[] = [
  {
    id: 'tx-9001',
    timestamp: '2026-02-11T16:40:00Z',
    type: 'receive',
    productName: products[1].name,
    sku: 'DS-4IN-BLU',
    lotNumber: 'LOT-2026-0160',
    quantity: 900,
    unitOfMeasure: 'each',
    toLocation: 'Magazine M-01',
    operator: 'A. Reyes',
    reference: 'SHIP-IN-3320',
    flags: [],
    sync: 'synced',
  },
  {
    id: 'tx-9002',
    timestamp: '2026-02-11T15:05:00Z',
    type: 'transfer',
    productName: products[5].name,
    sku: 'DS-8IN-GLD',
    lotNumber: 'LOT-2026-0155',
    quantity: -40,
    unitOfMeasure: 'each',
    fromLocation: 'Magazine M-01',
    toLocation: 'Magazine M-03',
    operator: 'J. Okafor',
    reference: 'MOVE-1187',
    flags: ['variance-detected'],
    sync: 'error',
  },
  {
    id: 'tx-9003',
    timestamp: '2026-02-11T11:20:00Z',
    type: 'issue',
    productName: products[0].name,
    sku: 'DS-6IN-RED',
    lotNumber: 'LOT-2026-0142',
    quantity: -120,
    unitOfMeasure: 'each',
    fromLocation: 'Magazine M-01',
    toLocation: 'Show SH-2041',
    operator: 'A. Reyes',
    reference: 'SH-2041',
    flags: [],
    sync: 'synced',
  },
  {
    id: 'tx-9004',
    timestamp: '2026-02-10T17:55:00Z',
    type: 'count-adjustment',
    productName: products[5].name,
    sku: 'DS-8IN-GLD',
    lotNumber: 'LOT-2026-0155',
    quantity: -3,
    unitOfMeasure: 'each',
    fromLocation: 'Magazine M-03',
    operator: 'System',
    reference: 'CNT-0442',
    flags: ['variance-detected', 'human-review-required'],
    sync: 'pending',
  },
  {
    id: 'tx-9005',
    timestamp: '2026-02-10T09:30:00Z',
    type: 'receive',
    productName: products[4].name,
    sku: 'IGN-EM-01',
    lotNumber: 'LOT-2026-0161',
    quantity: 5000,
    unitOfMeasure: 'each',
    toLocation: 'Magazine M-03',
    operator: 'M. Lindqvist',
    reference: 'SHIP-IN-3318',
    flags: [],
    sync: 'pending',
  },
  {
    id: 'tx-9006',
    timestamp: '2026-02-09T14:10:00Z',
    type: 'return',
    productName: products[0].name,
    sku: 'DS-6IN-RED',
    lotNumber: 'LOT-2026-0142',
    quantity: 18,
    unitOfMeasure: 'each',
    fromLocation: 'Show SH-2038',
    toLocation: 'Magazine M-01',
    operator: 'A. Reyes',
    reference: 'RET-2038',
    flags: ['review-required'],
    sync: 'synced',
  },
  {
    id: 'tx-9007',
    timestamp: '2026-02-08T10:00:00Z',
    type: 'disposal',
    productName: products[6].name,
    sku: 'ACC-QM-24',
    lotNumber: 'LOT-2025-0991',
    quantity: -250,
    unitOfMeasure: 'each',
    fromLocation: 'Magazine M-02',
    operator: 'Compliance Officer',
    reference: 'DISP-0075',
    flags: ['missing-documentation'],
    sync: 'synced',
  },
]

// ---------------------------------------------------------------------------
// Count sessions + lines + variances
// ---------------------------------------------------------------------------

export const countSessions: CountSession[] = [
  {
    id: 'cnt-0442',
    reference: 'CNT-0442',
    magazineId: 'm-03',
    magazineName: 'Magazine M-03',
    status: 'pending-review',
    startedAt: '2026-02-10T16:30:00Z',
    completedAt: '2026-02-10T17:45:00Z',
    countedBy: 'J. Okafor',
    linesTotal: 6,
    linesCounted: 6,
    variancesFound: 1,
  },
  {
    id: 'cnt-0443',
    reference: 'CNT-0443',
    magazineId: 'm-01',
    magazineName: 'Magazine M-01',
    status: 'in-progress',
    startedAt: '2026-02-12T08:05:00Z',
    countedBy: 'A. Reyes',
    linesTotal: 14,
    linesCounted: 9,
    variancesFound: 0,
  },
  {
    id: 'cnt-0441',
    reference: 'CNT-0441',
    magazineId: 'm-02',
    magazineName: 'Magazine M-02',
    status: 'reconciled',
    startedAt: '2026-02-08T09:00:00Z',
    completedAt: '2026-02-08T10:10:00Z',
    countedBy: 'M. Lindqvist',
    linesTotal: 9,
    linesCounted: 9,
    variancesFound: 0,
  },
]

export const countLines: CountLine[] = [
  {
    id: 'cl-1',
    lotNumber: 'LOT-2026-0155',
    productName: products[5].name,
    sku: 'DS-8IN-GLD',
    systemQty: 123,
    countedQty: 120,
    unitOfMeasure: 'each',
    variance: -3,
  },
  {
    id: 'cl-2',
    lotNumber: 'LOT-2026-0161',
    productName: products[4].name,
    sku: 'IGN-EM-01',
    systemQty: 5000,
    countedQty: 5000,
    unitOfMeasure: 'each',
    variance: 0,
  },
  {
    id: 'cl-3',
    lotNumber: 'LOT-2026-0170',
    productName: products[2].name,
    sku: 'CAKE-500-AST',
    systemQty: 12,
    countedQty: null,
    unitOfMeasure: 'each',
    variance: 0,
  },
]

export const varianceCases: VarianceCase[] = [
  {
    id: 'var-0442-1',
    reference: 'VAR-0091',
    countReference: 'CNT-0442',
    magazineName: 'Magazine M-03',
    productName: products[5].name,
    lotNumber: 'LOT-2026-0155',
    systemQty: 123,
    countedQty: 120,
    variance: -3,
    status: 'investigating',
    openedAt: '2026-02-10T17:50:00Z',
    assignedTo: 'Compliance Officer',
    flags: ['variance-detected', 'human-review-required'],
  },
  {
    id: 'var-0088',
    reference: 'VAR-0088',
    countReference: 'CNT-0439',
    magazineName: 'Magazine M-02',
    productName: products[3].name,
    lotNumber: 'LOT-2026-0151',
    systemQty: 225,
    countedQty: 220,
    variance: -5,
    status: 'pending-review',
    openedAt: '2026-02-05T12:00:00Z',
    assignedTo: 'Compliance Officer',
    flags: ['variance-detected', 'review-required'],
  },
]

// ---------------------------------------------------------------------------
// Inspection & daily close
// ---------------------------------------------------------------------------

export const inspectionChecklist: InspectionChecklistItem[] = [
  { id: 'ic-1', label: 'Structure & roof integrity', result: 'pass' },
  { id: 'ic-2', label: 'Door, hinges & locking hardware', result: 'pass' },
  { id: 'ic-3', label: 'Ventilation & moisture', result: 'attention', note: 'Minor condensation noted on north wall.' },
  { id: 'ic-4', label: 'Housekeeping & separation distances', result: 'pass' },
  { id: 'ic-5', label: 'Signage & markings legible', result: 'pass' },
  { id: 'ic-6', label: 'No unauthorized items present', result: 'pass' },
  { id: 'ic-7', label: 'Grounding / bonding (where applicable)', result: null },
]

export const magazineInspections: MagazineInspection[] = [
  {
    id: 'insp-201',
    reference: 'INSP-0201',
    magazineId: 'm-01',
    magazineName: 'Magazine M-01',
    inspectedBy: 'M. Lindqvist',
    performedAt: '2026-02-09T08:15:00Z',
    overallResult: 'pass',
    itemsPassed: 7,
    itemsTotal: 7,
    flags: [],
  },
  {
    id: 'insp-202',
    reference: 'INSP-0202',
    magazineId: 'm-02',
    magazineName: 'Magazine M-02',
    inspectedBy: 'J. Okafor',
    performedAt: '2026-02-03T08:00:00Z',
    overallResult: 'attention',
    itemsPassed: 6,
    itemsTotal: 7,
    flags: ['review-required'],
  },
  {
    id: 'insp-203',
    reference: 'INSP-0203',
    magazineId: 'm-04',
    magazineName: 'Magazine M-04',
    inspectedBy: 'A. Reyes',
    performedAt: '2026-01-28T10:00:00Z',
    overallResult: 'fail',
    itemsPassed: 4,
    itemsTotal: 7,
    flags: ['missing-documentation', 'human-review-required'],
  },
]

export const dailyCloseRecords: DailyCloseRecord[] = [
  {
    id: 'dc-1',
    date: '2026-02-11T18:30:00Z',
    magazineName: 'Magazine M-01',
    openingNewG: 1_360_500,
    closingNewG: 1_340_500,
    expectedNewG: 1_340_500,
    status: 'balanced',
    closedBy: 'A. Reyes',
    flags: [],
  },
  {
    id: 'dc-2',
    date: '2026-02-11T19:00:00Z',
    magazineName: 'Magazine M-03',
    openingNewG: 411_440,
    closingNewG: 410_000,
    expectedNewG: 411_440,
    status: 'variance-detected',
    closedBy: 'J. Okafor',
    flags: ['variance-detected', 'human-review-required'],
  },
  {
    id: 'dc-3',
    date: '2026-02-12T00:00:00Z',
    magazineName: 'Magazine M-02',
    openingNewG: 980_200,
    closingNewG: 980_200,
    expectedNewG: 980_200,
    status: 'pending',
    flags: ['review-required'],
  },
]

// ---------------------------------------------------------------------------
// Shows / packages / loadouts / returns
// ---------------------------------------------------------------------------

export const shows: Show[] = [
  {
    id: 'sh-2041',
    reference: 'SH-2041',
    name: 'Harbor Festival Finale (sample)',
    client: 'Harbor Events LLC (fictional)',
    venue: 'Bayfront Park (fictional)',
    date: '2026-02-15T22:00:00Z',
    status: 'packaging',
    leadOperator: 'A. Reyes',
    itemCount: 640,
    totalNewG: 512_400,
    flags: ['review-required'],
  },
  {
    id: 'sh-2042',
    reference: 'SH-2042',
    name: 'Winter Gala Display (sample)',
    client: 'Summit Hospitality (fictional)',
    venue: 'Grand Plaza (fictional)',
    date: '2026-02-20T21:30:00Z',
    status: 'planned',
    leadOperator: 'J. Okafor',
    itemCount: 380,
    totalNewG: 288_000,
    flags: [],
  },
  {
    id: 'sh-2038',
    reference: 'SH-2038',
    name: 'Founders Day Show (sample)',
    client: 'City of Rivermouth (fictional)',
    venue: 'Riverside Green (fictional)',
    date: '2026-02-08T21:00:00Z',
    status: 'reconciled',
    leadOperator: 'A. Reyes',
    itemCount: 512,
    totalNewG: 402_000,
    flags: [],
  },
  {
    id: 'sh-2044',
    reference: 'SH-2044',
    name: 'Corporate Launch (sample)',
    client: 'Lumen Dynamics (fictional)',
    venue: 'Innovation Campus (fictional)',
    date: '2026-02-25T20:00:00Z',
    status: 'in-field',
    leadOperator: 'M. Lindqvist',
    itemCount: 220,
    totalNewG: 176_500,
    flags: ['missing-documentation'],
  },
]

export const showPackageLines: ShowPackageLine[] = [
  {
    id: 'spl-1',
    productName: products[0].name,
    sku: 'DS-6IN-RED',
    lotNumber: 'LOT-2026-0142',
    quantityPlanned: 120,
    quantityPackaged: 120,
    unitOfMeasure: 'each',
  },
  {
    id: 'spl-2',
    productName: products[5].name,
    sku: 'DS-8IN-GLD',
    lotNumber: 'LOT-2026-0155',
    quantityPlanned: 40,
    quantityPackaged: 24,
    unitOfMeasure: 'each',
  },
  {
    id: 'spl-3',
    productName: products[2].name,
    sku: 'CAKE-500-AST',
    lotNumber: 'LOT-2026-0143',
    quantityPlanned: 12,
    quantityPackaged: 0,
    unitOfMeasure: 'each',
  },
  {
    id: 'spl-4',
    productName: products[4].name,
    sku: 'IGN-EM-01',
    lotNumber: 'LOT-2026-0161',
    quantityPlanned: 400,
    quantityPackaged: 400,
    unitOfMeasure: 'each',
  },
]

export const loadoutLines: LoadoutLine[] = [
  { id: 'll-1', productName: products[0].name, lotNumber: 'LOT-2026-0142', quantity: 120, scanned: true, containerRef: 'CTN-01' },
  { id: 'll-2', productName: products[5].name, lotNumber: 'LOT-2026-0155', quantity: 24, scanned: true, containerRef: 'CTN-01' },
  { id: 'll-3', productName: products[2].name, lotNumber: 'LOT-2026-0143', quantity: 12, scanned: false, containerRef: 'CTN-02' },
  { id: 'll-4', productName: products[4].name, lotNumber: 'LOT-2026-0161', quantity: 400, scanned: false, containerRef: 'CTN-02' },
]

export const returnLines: ReturnLine[] = [
  {
    id: 'rl-1',
    productName: products[0].name,
    lotNumber: 'LOT-2026-0142',
    quantityLoaded: 120,
    quantityFired: 100,
    quantityReturned: 18,
    quantityUnaccounted: 2,
    flags: ['review-required'],
  },
  {
    id: 'rl-2',
    productName: products[5].name,
    lotNumber: 'LOT-2026-0155',
    quantityLoaded: 24,
    quantityFired: 24,
    quantityReturned: 0,
    quantityUnaccounted: 0,
    flags: [],
  },
  {
    id: 'rl-3',
    productName: products[2].name,
    lotNumber: 'LOT-2026-0143',
    quantityLoaded: 12,
    quantityFired: 10,
    quantityReturned: 0,
    quantityUnaccounted: 2,
    flags: ['variance-detected', 'human-review-required'],
  },
]

// ---------------------------------------------------------------------------
// Shipments
// ---------------------------------------------------------------------------

export const shipments: Shipment[] = [
  {
    id: 'ship-3320',
    reference: 'SHIP-IN-3320',
    direction: 'inbound',
    status: 'received',
    counterparty: 'Northwind Pyrotechnics (fictional)',
    carrier: 'HazFreight Lines (fictional)',
    expectedDate: '2026-02-11T12:00:00Z',
    lineCount: 3,
    totalNewG: 210_000,
    flags: [],
  },
  {
    id: 'ship-3321',
    reference: 'SHIP-IN-3321',
    direction: 'inbound',
    status: 'in-transit',
    counterparty: 'Summit Effects Co. (fictional)',
    carrier: 'HazFreight Lines (fictional)',
    expectedDate: '2026-02-13T09:00:00Z',
    lineCount: 5,
    totalNewG: 640_000,
    flags: ['review-required'],
  },
  {
    id: 'ship-out-1180',
    reference: 'SHIP-OUT-1180',
    direction: 'outbound',
    status: 'dispatched',
    counterparty: 'Harbor Events LLC (fictional)',
    carrier: 'Internal Transport',
    expectedDate: '2026-02-15T14:00:00Z',
    lineCount: 4,
    totalNewG: 512_400,
    flags: [],
  },
  {
    id: 'ship-in-3315',
    reference: 'SHIP-IN-3315',
    direction: 'inbound',
    status: 'exception',
    counterparty: 'Ridgeline Powder (fictional)',
    carrier: 'HazFreight Lines (fictional)',
    expectedDate: '2026-02-09T10:00:00Z',
    lineCount: 2,
    totalNewG: 90_000,
    flags: ['missing-documentation', 'potential-conflict'],
  },
]

// ---------------------------------------------------------------------------
// Compliance / documents / audit
// ---------------------------------------------------------------------------

export const complianceItems: ComplianceItem[] = [
  {
    id: 'ci-1',
    reference: 'CR-0311',
    subject: 'Count variance requires disposition',
    relatedTo: 'Magazine M-03 / CNT-0442',
    flag: 'variance-detected',
    raisedAt: '2026-02-10T17:55:00Z',
    assignedTo: 'Compliance Officer',
    status: 'in-review',
    detail:
      'A physical count recorded fewer units than the system total for lot LOT-2026-0155. Human review and disposition required before the count can be reconciled.',
  },
  {
    id: 'ci-2',
    reference: 'CR-0312',
    subject: 'Inbound shipment missing paperwork',
    relatedTo: 'SHIP-IN-3315',
    flag: 'missing-documentation',
    raisedAt: '2026-02-09T10:30:00Z',
    assignedTo: 'Compliance Officer',
    status: 'open',
    detail:
      'Shipping paper reference was not attached at receipt. Documentation must be located or requested before the shipment is cleared.',
  },
  {
    id: 'ci-3',
    reference: 'CR-0313',
    subject: 'Overlapping magazine assignment detected',
    relatedTo: 'Magazine M-02',
    flag: 'potential-conflict',
    raisedAt: '2026-02-08T14:20:00Z',
    status: 'open',
    detail:
      'Two lots reference conflicting storage groups for the same magazine bay. Requires human review to confirm intended placement.',
  },
  {
    id: 'ci-4',
    reference: 'CR-0310',
    subject: 'Inspection overdue',
    relatedTo: 'Magazine M-02',
    flag: 'review-required',
    raisedAt: '2026-02-12T07:00:00Z',
    assignedTo: 'M. Lindqvist',
    status: 'open',
    detail: 'Next inspection date has passed. Schedule and record an inspection to clear this item.',
  },
]

export const documents: DocumentRecord[] = [
  {
    id: 'doc-1',
    title: 'Site Storage License (SAMPLE)',
    kind: 'license',
    relatedTo: 'Facility',
    uploadedBy: 'Compliance Officer',
    uploadedAt: '2025-09-01T00:00:00Z',
    expiresAt: '2026-08-31T00:00:00Z',
    status: 'valid',
    sizeKb: 842,
  },
  {
    id: 'doc-2',
    title: 'Magazine M-02 Inspection Report',
    kind: 'inspection-report',
    relatedTo: 'Magazine M-02',
    uploadedBy: 'J. Okafor',
    uploadedAt: '2026-02-03T09:00:00Z',
    status: 'valid',
    sizeKb: 320,
  },
  {
    id: 'doc-3',
    title: 'Shipping Paper SHIP-IN-3315',
    kind: 'shipping-paper',
    relatedTo: 'SHIP-IN-3315',
    uploadedBy: '—',
    uploadedAt: '2026-02-09T10:00:00Z',
    status: 'missing',
    sizeKb: 0,
  },
  {
    id: 'doc-4',
    title: 'Operator Training Record — A. Reyes',
    kind: 'training-record',
    relatedTo: 'Personnel',
    uploadedBy: 'Admin',
    uploadedAt: '2025-06-15T00:00:00Z',
    expiresAt: '2026-03-01T00:00:00Z',
    status: 'expiring',
    sizeKb: 210,
  },
  {
    id: 'doc-5',
    title: 'SDS — 3Fg Black Powder',
    kind: 'sds',
    relatedTo: 'LIFT-3F-BP',
    uploadedBy: 'Admin',
    uploadedAt: '2024-02-01T00:00:00Z',
    expiresAt: '2025-02-01T00:00:00Z',
    status: 'expired',
    sizeKb: 156,
  },
]

export const auditEvents: AuditEvent[] = [
  {
    id: 'ae-1',
    timestamp: '2026-02-11T16:40:12Z',
    actor: 'A. Reyes',
    action: 'Received inventory',
    entity: 'Lot',
    entityRef: 'LOT-2026-0160',
    detail: '+900 each into Magazine M-01 (ref SHIP-IN-3320)',
    channel: 'mobile',
  },
  {
    id: 'ae-2',
    timestamp: '2026-02-11T15:05:44Z',
    actor: 'J. Okafor',
    action: 'Initiated transfer',
    entity: 'Movement',
    entityRef: 'MOVE-1187',
    detail: 'M-01 → M-03, 40 each of DS-8IN-GLD',
    channel: 'mobile',
  },
  {
    id: 'ae-3',
    timestamp: '2026-02-10T17:50:03Z',
    actor: 'System',
    action: 'Flagged variance',
    entity: 'Count',
    entityRef: 'CNT-0442',
    detail: 'Variance -3 detected on LOT-2026-0155; human review required',
    channel: 'system',
  },
  {
    id: 'ae-4',
    timestamp: '2026-02-10T09:00:21Z',
    actor: 'Compliance Officer',
    action: 'Opened compliance item',
    entity: 'Compliance',
    entityRef: 'CR-0312',
    detail: 'Missing shipping paper for SHIP-IN-3315',
    channel: 'web',
  },
  {
    id: 'ae-5',
    timestamp: '2026-02-09T08:20:10Z',
    actor: 'M. Lindqvist',
    action: 'Completed inspection',
    entity: 'Inspection',
    entityRef: 'INSP-0201',
    detail: 'Magazine M-01 — result: pass (7/7)',
    channel: 'mobile',
  },
]

// ---------------------------------------------------------------------------
// Administration & reports
// ---------------------------------------------------------------------------

export const users: UserAccount[] = [
  {
    id: 'u-1',
    name: 'A. Reyes',
    email: 'a.reyes@example-pyro.test',
    role: 'operator',
    active: true,
    lastActive: '2026-02-12T08:10:00Z',
    assignedSites: ['West Yard'],
  },
  {
    id: 'u-2',
    name: 'J. Okafor',
    email: 'j.okafor@example-pyro.test',
    role: 'magazine-keeper',
    active: true,
    lastActive: '2026-02-12T07:50:00Z',
    assignedSites: ['East Yard'],
  },
  {
    id: 'u-3',
    name: 'M. Lindqvist',
    email: 'm.lindqvist@example-pyro.test',
    role: 'compliance-officer',
    active: true,
    lastActive: '2026-02-11T20:00:00Z',
    assignedSites: ['West Yard', 'East Yard', 'North Pad'],
  },
  {
    id: 'u-4',
    name: 'D. Chen',
    email: 'd.chen@example-pyro.test',
    role: 'admin',
    active: true,
    lastActive: '2026-02-12T06:30:00Z',
    assignedSites: ['All'],
  },
  {
    id: 'u-5',
    name: 'P. Novak',
    email: 'p.novak@example-pyro.test',
    role: 'viewer',
    active: false,
    lastActive: '2026-01-30T14:00:00Z',
    assignedSites: ['West Yard'],
  },
]

export const reportDefinitions: ReportDefinition[] = [
  {
    id: 'rep-1',
    name: 'Current Inventory by Magazine',
    description: 'On-hand quantities and net explosive weight grouped by magazine.',
    category: 'inventory',
    lastRun: '2026-02-11T20:00:00Z',
    format: 'xlsx',
  },
  {
    id: 'rep-2',
    name: 'Transaction Ledger Export',
    description: 'All movements for a selected date range with operator and reference.',
    category: 'operations',
    lastRun: '2026-02-10T18:00:00Z',
    format: 'csv',
  },
  {
    id: 'rep-3',
    name: 'Daily Close Summary',
    description: 'Opening/closing balances and variance status per magazine per day.',
    category: 'operations',
    lastRun: '2026-02-11T19:30:00Z',
    format: 'pdf',
  },
  {
    id: 'rep-4',
    name: 'Open Compliance Items',
    description: 'Items flagged for human review with status and assignment.',
    category: 'compliance',
    format: 'pdf',
  },
  {
    id: 'rep-5',
    name: 'Audit History Export',
    description: 'Chronological record of actions across web, mobile, and system.',
    category: 'audit',
    lastRun: '2026-02-09T00:00:00Z',
    format: 'csv',
  },
  {
    id: 'rep-6',
    name: 'Variance Investigations',
    description: 'Open and resolved variance cases with disposition detail.',
    category: 'compliance',
    format: 'xlsx',
  },
]

// ---------------------------------------------------------------------------
// Dashboard aggregates (precomputed sample figures)
// ---------------------------------------------------------------------------

export const dashboardStats = {
  totalNewG: 2_730_700,
  magazinesOperational: 2,
  magazinesTotal: 4,
  openComplianceItems: 4,
  pendingSync: 3,
  variancesOpen: 2,
  inspectionsDue: 1,
  showsUpcoming: 2,
}

export const newTrend = [
  { day: 'Feb 5', new: 2_610_000 },
  { day: 'Feb 6', new: 2_695_500 },
  { day: 'Feb 7', new: 2_705_500 },
  { day: 'Feb 8', new: 2_455_500 },
  { day: 'Feb 9', new: 2_473_500 },
  { day: 'Feb 10', new: 2_470_500 },
  { day: 'Feb 11', new: 2_730_700 },
]
